apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-role
  namespace: argocd
  resourceVersion: "4939"
  uid: ca0c16f8-a4e9-4624-b510-5f097c2d142d
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
